### ISSUE TITLE
Problem with kafka

### ISSUE THREAD

**Issue by fernandofreije** [Arquisoft/dashboard_i3a#1]
The project launchs an exception when we run it even if we have kafka running and configured correctly.

**Comment by pablogarciamiranda** [comment]
## Kafka is now able to produce and consume

We have edited the start_kafka.bat file and we have splitted the execution of Kafka into two different consoles with a timeout of 10 seconds. 

We have three different files

- **start_zookeeper.bat**: Starts a quick-and-dirty single-node ZooKeeper instance.

- **start_kafka.bat**: Starts the Kafka server.

- **launch.bat**: Run the two previous scripts.

Now we are able to produce messages and consume them in console by a logger.
