### ISSUE TITLE
Problem with statistic bars

### ISSUE THREAD

**Issue by dgsama** [Arquisoft/dashboard_i3a#3]
I have to assign dinamically the value of the width taking the result of a thymeleaf expression.

`<div class="progress-bar progress-bar-success"
role="progressbar" aria-valuenow="${proposal.votesInfoRangoEdad.adultgPerNo}"
 aria-valuemin="0" aria-valuemax="100" style="width: 30%"
th:text="${proposal.votesInfoRangoEdad.adultgPerNo}"></div>`

**Comment by dgsama** [comment]
We have a solution, example:

`th:style="'width:'+ ${proposal.votesInfoGenero.malePerNo}+'%;'"`

**Comment by pablogarciamiranda** [comment]
We asked in stackoverflow for help but it was not successful:
http://stackoverflow.com/questions/43171660/adjust-width-of-progress-bars-dynamically
